# Generated by Django 4.0.4 on 2022-05-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('how_did_you_hear', models.CharField(choices=[('friend', 'Friend'), ('internet', 'Internet'), ('performance', 'Performance'), ('recruited', 'Recruited'), ('other', 'Other')], max_length=255)),
                ('what_attracted_you', models.CharField(choices=[('looks fun', 'Looks Fun'), ('culture', 'Culture'), ('physical activity', 'Physical Activity'), ('something new', 'Something New'), ('everything', 'Everything')], max_length=255)),
                ('interest_in_lion_dance', models.CharField(choices=[('head', 'Head'), ('tail', 'Tail'), ('martial arts', 'Martial Arts'), ('music', 'Music'), ('everything', 'Everything')], max_length=255)),
                ('level_of_interest', models.CharField(choices=[('somewhat', 'Somewhat'), ('interested', 'Interested'), ('very interested', 'Very Interested')], max_length=255)),
            ],
        ),
    ]
