# Generated by Django 4.0.4 on 2022-05-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('class_year', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='how_did_you_hear',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='interest_in_lion_dance',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='level_of_interest',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='what_attracted_you',
            field=models.CharField(max_length=255),
        ),
    ]
