# Generated by Django 4.0.4 on 2024-01-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_memberentry_alter_application_how_did_you_hear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='how_did_you_hear',
            field=models.CharField(choices=[('friend', 'Friend'), ('internet', 'Internet'), ('performance', 'Performance'), ('recruited', 'Recruited'), ('other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='interest_in_lion_dance',
            field=models.CharField(choices=[('head', 'Head'), ('tail', 'Tail'), ('martial arts', 'Martial Arts'), ('music', 'Music'), ('everything', 'Everything')], max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='level_of_interest',
            field=models.CharField(choices=[('somewhat', 'Somewhat'), ('interested', 'Interested'), ('very interested', 'Very Interested')], max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='what_attracted_you',
            field=models.CharField(choices=[('looks fun', 'Looks Fun'), ('culture', 'Culture'), ('physical activity', 'Physical Activity'), ('something new', 'Something New'), ('everything', 'Everything')], max_length=255),
        ),
    ]
